#%RAML 1.0 NamedExample


value:
  accountID: "1SA213QR"
  IBAN: "ABCD 1232 WQERT 1QAR 11"
  BIC: "AAAAA"
  accountDescription: "This is a corporate account"
  accountType:  "Current"
  ledgerBalance: 100000
  avaliableBalance: 1000000
  accountStatus: "Active"