#%RAML 1.0
title: ConsentTemenos

securitySchemes:
  oauth2.0: !include securityScheme.raml

securedBy: [oauth2.0]

/consentPopulate:
  description: Get consent information
  get:
    headers:
      Location:
    queryParameters:

    responses:
      200:
        body:
          application/json:
            
      400:
        body:
          application/json:
 
  post:
    description: Store Consent Information
    headers:
    queryParameters:

    responses:
      200:
      400:   
  
  /{permissionID}:
    get:
      headers:
      queryParameters:
        AccountIDs:
        SessionID:
        
    post:
      headers:
      queryParameters:


